### PR TITLE
fix: convert eslint plugin 'require()' to 'import'

### LINKED ISSUE #3199: eslint-plugin-mobx does not work
I really like the idea of using ```eslint``` to prevent some common / simple issues in code related to ```mobx``` use. However, current version of ```eslint-plugin-mobx``` does not seem to be working at all.

**Intended outcome:**

* Follow installation instructions
* Run ```eslint```
* Receive information that there are some problems with code (or not)

**Actual outcome:**

While installation and configuration of ```eslint-plugin-mobx``` went without any issues, running ```eslint``` produces following message

```cmd
Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the plugin "eslint-plugin-mobx".

(The package "eslint-plugin-mobx" was not found when loaded as a Node module from the directory "......\test-eslint-plugin-mobx".)
```

**How to reproduce the issue:**

Just following provided plugin installation steps seems to be enough.

I have reviewed installed module and I think there might be a problem how it was packaged. Just to check that this is not some configuration issue, I *hacked* ```node_modules\eslint-plugin-mobx\package.json``` file by adding following line and plugin was found by ```eslint```:

```
"main": "src/index.js",
```

But now I got another error:

```cmd
Oops! Something went wrong! :(

ESLint: 7.32.0

......\test-eslint-plugin-mobx\node_modules\eslint-plugin-mobx\src\utils.js:20
    error ??= 'Assertion failed';
          ^^^

SyntaxError: Unexpected token '??='
    at new Script (vm.js:102:7)
    at NativeCompileCache._moduleCompile (......\test-eslint-plugin-mobx\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (......\test-eslint-plugin-mobx\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (......\test-eslint-plugin-mobx\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (......\test-eslint-plugin-mobx\node_modules\eslint-plugin-mobx\src\exhaustive-make-observable.js:3:43)
    at Module._compile (......\test-eslint-plugin-mobx\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
```

### PR DESCRIPTION
**Pull request by ltdu**
fixes #3199

There is basically no change to code itself, just conversion to TypeScript

### CODE REVIEW

**Comment by urugator** [comment]
It's intentionally not written in TS. The reason is that during development, I can see how the plugin actually works, just by reloading the IDE window (forcing it to reload the eslint plugin). See the `preview` folder:
plugin-preview

I could probably require compiled `index.js` from `dist` instead of `src`, but in addition to reloading window, I would have to always run build before, which I would like to avoid.

Besided that I don't think TS provides much value here (more likely being a hinderance).

**Comment by iChenLei** [comment]
Agree with @urugator

**Comment by ltdu** [comment]
This PR is only one possible solution to the problem. Of course there are others.

I consider this to be an issue with package build process. Most likely during build only ```index.ts``` file is picked up and compiled. All other ```require('*.js')``` statements are treated as importing some static JavaScript. You could update ```tsconfig.json``` to include directives to compile JS files as well. Something like this:

```
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "rootDir": "src",
        "allowJs": true
    },
    "include": [
        "src"
    ]
}
```

Either way, I am waiting with anticipation for this issue to be resolved, so that I could try it out in real full scale projects

**Comment by urugator** [comment]
>  You could update tsconfig.json to include directives to compile JS files

That's something I would like to get to, but I can't get it working, any help appreciated.

> Most likely during build only index.ts file is picked up and compiled.

I thought that as well, but the output seems to be actually created directly from `index.js`. I tried to:
rename `index.js` to `_index.js` (to make sure it picks `index.ts`) 
-> `index.ts` complains about `export * from './_index.js';` not being possible (interestingly it did not complained with `./index.js`)
-> changed it to `import * as _index from './_index.js';` (dunno how to reexport this)
-> builds, but `require` calls are still present

**Comment by ltdu** [comment]
I have renamed ```*.ts``` files back to ```*.js``` and build process produces correct bundles. Could you try your development process? Maybe changing how ```imports``` are handled will be enough to solve this.

**Comment by urugator** [comment]
IIRC eslint wasn't able to load plugin written as ES module, it had to be commonjs, but i will try.

**Comment by urugator** [comment]
```
[Info  - 14:09:09] ESLint server is starting
[Info  - 14:09:10] ESLint server running in node v14.16.0
[Info  - 14:09:10] ESLint server is running.
[Info  - 14:09:14] ESLint library loaded from: C:\Projects\tmp\mobx\packages\eslint-plugin-mobx\node_modules\eslint\lib\api.js
[Error - 14:09:14] ESLint stack trace:
[Error - 14:09:14] C:\Projects\tmp\mobx\packages\eslint-plugin-mobx\src\index.js:3
import exhaustiveMakeObservable from "./exhaustive-make-observable"
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1033:16)
    at Module._compile (internal/modules/cjs/loader.js:1081:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Projects\tmp\mobx\packages\eslint-plugin-mobx\preview\node_modules\eslint-plugin-mobx\index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
```
And if try to change it into module by adding `preview/node_modules/eslint-plugin-mobx/package.json` with `"type": "module"`
```
[Info  - 14:14:28] ESLint server is starting
[Info  - 14:14:29] ESLint server running in node v14.16.0
[Info  - 14:14:29] ESLint server is running.
[Info  - 14:14:31] ESLint library loaded from: C:\Projects\tmp\mobx\packages\eslint-plugin-mobx\node_modules\eslint\lib\api.js
[Error - 14:14:31] ESLint stack trace:
[Error - 14:14:31] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Projects\tmp\mobx\packages\eslint-plugin-mobx\preview\node_modules\eslint-plugin-mobx\index.js
require() of ES modules is not supported.
require() of C:\Projects\tmp\mobx\packages\eslint-plugin-mobx\preview\node_modules\eslint-plugin-mobx\index.js from C:\Projects\tmp\mobx\node_modules\@eslint\eslintrc\lib\config-array-factory.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Projects\tmp\mobx\packages\eslint-plugin-mobx\preview\node_modules\eslint-plugin-mobx\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:13)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at ConfigArrayFactory._loadPlugin (C:\Projects\tmp\mobx\node_modules\@eslint\eslintrc\lib\config-array-factory.js:1036:42)
    at ConfigArrayFactory._loadExtendedPluginConfig (C:\Projects\tmp\mobx\node_modules\@eslint\eslintrc\lib\config-array-factory.js:837:29)
    at ConfigArrayFactory._loadExtends (C:\Projects\tmp\mobx\node_modules\@eslint\eslintrc\lib\config-array-factory.js:779:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Projects\tmp\mobx\node_modules\@eslint\eslintrc\lib\config-array-factory.js:720:25)
```

**Comment by ltdu** [comment]
Sorry, it seems I won't be able to provide any more useful input. Maybe someone from community will be able to chip in.

**Comment by urugator** [comment]
@ltdu Thanks for your time and input anyway. I wonder if it's even doable with the current setup/toolchain. For the time being let's leave this PR open.

**Comment by ltdu** [comment]
Because packaging issue is now [solved](https://github.com/mobxjs/mobx/pull/3204), I'm closing this as not needed any more

**Pull request closed without merging**
