### PR TITLE
docs: updated Canva logo

### PR DESCRIPTION
**Pull request by mykola-rykov**
👋 This PR is a change to documentation only.
It introduces an updated [Canva](https://www.canva.com/) logo according to the latest Canva brand style.
Thank you!

### CODE REVIEW

**Comment by kubk** [comment]
Thank you

**Comment by mykola-rykov** [comment]
Hi @kubk! There is one thing that can possibly not deploy automatically - in this PR I assumed that all static assets from `/docs/assets/*` are automatically uploaded & available at `https://mobx.js.org/assets/*`. Is that true? If not then can you please make the new `/docs/assets/canva.svg` asset available at `https://mobx.js.org/assets/canva.svg`?
Thank you again!

**Comment by kubk** [comment]
@mykola-rykov It seems like the entire deployment is not functioning, as my last documentation update has also not been deployed. We will try to find a solution and let you know once it is fixed. Thank you 👍

**Comment by mweststrate** [comment]
It seems the webhook stopped working. I reconfigured it, and it deploys succesfully. Hopefully it keeps working now :)

**Comment by mweststrate** [comment]
Apologies for the delay @mykola-rykov!

**Comment by mykola-rykov** [comment]
Thank you very much @kubk @mweststrate!
P.S. MobX is awesomely great in so many ways!

**Pull request merged**
