### PR TITLE
[action/createAction] - Keep observable reference.

### PR DESCRIPTION
**Pull request by ItamarShDev**
fix issue #1887

### CODE REVIEW

**Comment by ItamarShDev** [comment]
@mweststrate Not sure if this is the best solution.
Will be happy for some input

**Comment by mweststrate** [comment]
Thanks for picking up! I think the code would be slightly easier to follow, if `scope` is an optional third argument to `createAction`, and pass it in from the relevant `defineBoundAction` calls explicitly. (Possibly the `bind` there becomes optional as well then).  

Could you also add some unit tests verifying the original bug?

Thanks a lot!

**Comment by ItamarShDev** [comment]
Sure, will do

**Comment by ItamarShDev** [comment]
@mweststrate updated, what do you think about this approach?

**Comment by mweststrate** [comment]
@ItamarShDev looking good! approved

**Pull request merged**
