### PR TITLE
refactor(mobx): remove the function updateHasMapEntry_

### PR DESCRIPTION
**Pull request by rluvaton**
### Code change checklist

-   [ ] Added/updated unit tests
-   [ ] Updated `/docs`. For new functionality, at least `API.md` should be updated
-   [ ] Verified that there is no significant performance drop (`npm run perf`)

### CODE REVIEW

**Comment by rluvaton** [comment]
_Coverall / Packages coverage_ failed because of `405 Not Allowed`, I assume it would affect other PRs as well, you might wanna take a look at it

**Comment by iChenLei** [comment]
@rluvaton Thanks, I know it and report overalls's issue at mobxjs team chat channel.

**Comment by urugator** [comment]
Btw I think you can change it to oneliner:
`this.hasMap_.get(key)?.setNewValue_(value)`
and remove the method altogether, replacing
https://github.com/mobxjs/mobx/blob/e5c4c9f9fccd1479cad2e92f48f58ef8373b6e7f/packages/mobx/src/types/observablemap.ts#L181
https://github.com/mobxjs/mobx/blob/e5c4c9f9fccd1479cad2e92f48f58ef8373b6e7f/packages/mobx/src/types/observablemap.ts#L236

**Comment by rluvaton** [comment]
@urugator thanks!, I've updated

**Comment by iChenLei** [comment]
so .... change the pull request title ? Thanks @rluvaton

**Comment by rluvaton** [comment]
I've changed it...

**Comment by iChenLei** [comment]
Rerun Coveralls ci, all ci passed !

**Pull request merged**
