### PR TITLE
Converted the 4 most simple test files

### PR DESCRIPTION
**Pull request by gilamran**
### Code change checklist

-   [X] Added/updated unit tests
-   [ ] Updated changelog
-   [ ] Updated `/docs`. For new functionality, at least `API.md` should be updated
-   [ ] Verified that there is no significant performance drop (`npm run perf`)

### CODE REVIEW

**Comment by FredyC** [comment]
Thanks. I think it would be probably best to keep v4 and v5 in sync. Most tests are copy & paste, so please do the same changes in the v4 folder.

**Comment by gilamran** [comment]
Sure, will do

**Comment by FredyC** [comment]
Thanks, keep em coming if you like :)

**Comment by gilamran** [comment]
Cool, I'll move on to bigger and bigger tests.
While I'm in the process of conversion, I'll also upgrade the code to be more es6 "friendly"

**Pull request merged**
