### PR TITLE
Update docs for #2011

### PR DESCRIPTION
**Pull request by jillesme**
https://github.com/mobxjs/mobx/pull/2011

### CODE REVIEW

**Comment by FredyC** [comment]
This should be probably merged after #2014 is published.

**Comment by jillesme** [comment]
When will it be published?

**Comment by FredyC** [comment]
@xaviergonz @ItamarShDev Do you have publishing rights or it's up to Michel?

**Comment by xaviergonz** [comment]
I have publishing rights (though I can't grant them), but I think this is a good opportunity for @ItamarShDev to give it a try ;)

**Comment by xaviergonz** [comment]
Btw, how come the build failed? is this branch out of a branch before the circle-ci stuff was added?

**Comment by FredyC** [comment]
Well, this is `gh-pages` branch, circle-ci is not configured here at all and it's not needed. Not sure if it can be silenced for specific branches.

**Comment by jillesme** [comment]
Hey guys, any idea on when this will be released? 

We're currently doing this across the whole codebase, and then spying on the "private" method: 

image

No pressure, I value your time as open-source maintainers!

**Pull request merged**
