### PR TITLE
[undecorate] fix: non-null assertion operator is removed

### PR DESCRIPTION
**Pull request by urugator**
https://github.com/mobxjs/mobx/discussions/3615

`yarn upgrade` throws 
`error An unexpected error occurred: "expected workspace package to exist for \"jsonfile\"".`

~~So the only way to upgrade deps for me is to delete `yarn.lock` and `yarn install`. Therefore the `yarn.lock` changes.~~
Solved by removing and reintroducing jscodeshift dep.

### CODE REVIEW

**Comment by iChenLei** [comment]
https://github.com/mobxjs/mobx/blob/main/.github/workflows/build_and_test.yml#L3

```yaml
name: Build and test

on: ["push"]
```

PRs submitted by contributors do not trigger CI, causing trouble for code review. We can only see the CI in the contributors' own repository or after merging the code. Is there a good way to solve this problem?

> Current PR



> urugator's forked repository:



cc @kubk @urugator

**Comment by kubk** [comment]
@urugator Could you replace

```
on: ["push"]
```

with

```
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
```

here: https://github.com/mobxjs/mobx/blob/main/.github/workflows/build_and_test.yml#L3

Hope it'll help.

**Comment by kubk** [comment]
> PRs submitted by contributors do not trigger CI,

@iChenLei The new CI was triggered for my PR here: https://github.com/mobxjs/mobx/pull/3610

But yes, it might be due to that line. Let's see if changing it works for @urugator.

**Comment by iChenLei** [comment]
| type | screenshot |
| :--: | :--: |
| fork |  |
| non-fork(trigger `push` event) |  | 

That's why this PR not trigger CI.
cc @kubk

**Review by iChenLei — APPROVED** [review]

**Review by kubk — APPROVED** [review]

**Pull request merged**
