### PR TITLE
minor typings improvement

### PR DESCRIPTION
**Pull request by ssured**
Thanks for taking the effort to create a PR!

If you are creating an extensive PR, you might want to open an issue with your idea first, so that you don't put a lot of effort in an PR that wouldn't be accepted. Please prepend pull requests with `WIP: ` if they are not yet finished
PR checklist:

* [ ] Added unit tests
* [ ] Updated changelog
* [ ] Updated docs (either in the description of this PR as markdown, or as separate PR on the `gh-pages` branch. Please refer to this PR). For new functionality, at least [API.md](https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md) should be updated
* [ ] Added typescript typings
* [ ] Verified that there is no significant performance drop (`npm run perf`)

Feel free to ask help with any of these boxes!

The above process doesn't apply to doc updates etc.

### CODE REVIEW

**Comment by FredyC** [comment]
What's the use cases for that? Can you show some code, please?

**Comment by ssured** [comment]
`entries` is an API method which provides an iterator over the key-value combinations of an object.

This PR allows for:

```
const data = observable<{[key: string]: number}>({
a: 1,
b: 2
});

for (const [prop, value] of entries(data)) {
  // prop is of type string
  // value is of type number. Without the fix value would be of type any
}
```

**Comment by FredyC** [comment]
Alright, thanks for explanation and contribution.

**Comment by ssured** [comment]
Nice, thanks!

**Pull request merged**
