### PR TITLE
Expection -> Expecting

### PR DESCRIPTION
**Pull request by ncammarata**
I ran into this error while doing some MobX code writing. I'm actually not sure Expecting is the correct word here. I assumed my best guess as a PR was better than an issue pointing to the typo.

### CODE REVIEW

**Comment by capaj** [comment]
it is indeed correct word, `expection` does not exist. We should merge this. Only problem is this changes the Error message that is thrown. So it should probably be released in a new major. If it were just up 2 me, I'd probably just merge it, because it is not very likely that anyone is depending on the message of that error. But we certainly need to get more opinions on this- what do you think @mweststrate @tetsuo @andykog, anyone else?

**Comment by andykog** [comment]
@capaj, don't see any problems in merging this. Depending on error's message is not good way to go any way (btw, I'm using [EnhancedError](https://github.com/andykog/enhancederror) because of this), and this message is not mentioned anywhere in the docs.

**Comment by capaj** [comment]
@andykog cool, one more vote for and I'll merge this

**Comment by ncammarata** [comment]
I'm perhaps biased, but waiting on a major release for an error typo fix seems overkill. I'd vote to merge.

**Comment by mweststrate** [comment]
Yeah feel free to merge. People shouldn't depend on the exact spelling of an error message...

**Pull request merged**
