### PR TITLE
Fix flow typings [requires TS3.6]

### PR DESCRIPTION
**Pull request by xaviergonz**
Fixes typings for flows (actually even improves them), but requires TS3.6 to use flows.

If you don't want to merge it now maybe just consider leaving it there for the future.

### CODE REVIEW

**Comment by mweststrate** [comment]
I think we could release this as minor pretty soon, once we didn't have any patches for a couple of weeks

**Comment by xaviergonz** [comment]
Also fixed async generators while at it

**Comment by xaviergonz** [comment]
One question, there's a way to enforce TS typings so flow() has to always yield promises, would this be nice to have?

**Comment by mweststrate** [comment]
Published as 5.15.0

**Pull request merged**
