### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codemilli**
fix a broken link

### CODE REVIEW

**Comment by codemilli** [comment]
@FredyC applied

**Comment by FredyC** [comment]
Thanks. Now thinking about it, the link should probably point directly to https://mobx.js.org/best/react.html instead of github source. Not sure why it was like that before.

**Comment by FredyC** [comment]
Apply to both READMEs please 🙈

**Comment by FredyC** [comment]
Thanks a lot!

**Pull request merged**
