### PR TITLE
Use circleci instead of travis for ci

### PR DESCRIPTION
**Pull request by pustovalov**
Demo:

https://circleci.com/gh/pustovalov/mobx
https://coveralls.io/github/pustovalov/mobx

### CODE REVIEW

**Comment by pustovalov** [comment]
@xaviergonz WDYT?

**Comment by capaj** [comment]
@pustovalov is it faster than travis with all that caching config?

**Comment by pustovalov** [comment]
Travis: 4 min 2 sec
https://travis-ci.org/pustovalov/mobx/builds/544609273

CircleCI: 02:36

**Comment by FredyC** [comment]
Hey, where can I actually see that nice workflow view? I only see the list of builds which is somewhat hard to navigate.

**Comment by xaviergonz** [comment]
Click on the link below workflow
E. G. 
Workflow:
build-and-test

**Comment by FredyC** [comment]
Alright, 3 approvals, I am going to hit it :)

@xaviergonz Can you please do necessary setup as before? Thanks.

**Comment by xaviergonz** [comment]
Sure, will take me a few hours again though

**Comment by xaviergonz** [comment]
looking good:

https://circleci.com/workflow-run/019d8b12-9f0d-436e-9541-80b979bf3052

doesn't this need to be backported to the mobx 4 branch though? I'm weary of completely disabling the travis ci plugin until that's done

**Pull request merged**
