### PR TITLE
implement observable set

### PR DESCRIPTION
**Pull request by newraina**
This is a follow up to the issue: #69

PR checklist:

* [x] Added unit tests
* [ ] Updated changelog
* [ ] Updated docs (either in the description of this PR as markdown, or as separate PR on the `gh-pages` branch. Please refer to this PR). For new functionality, at least [API.md](https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md) should be updated
* [x] Added typescript typings
* [x] Verified that there is no significant performance drop (`npm run perf`)

### CODE REVIEW

**Comment by xaviergonz** [comment]
@newraina just wondering, what's left to implement this feature?

**Comment by newraina** [comment]
@xaviergonz doc and changelog update in the PR checklist... sorry for delay so long

**Comment by xaviergonz** [comment]
@newraina if that's the only thing that's left I could lend you a hand if you want

**Comment by newraina** [comment]
@xaviergonz  
OK, I will review my implementation again, handle git conflict, if everything is ok, I'll remove the 'WIP' title. maybe the doc/changelog update should in a separate PR?

**Comment by mweststrate** [comment]
Apologies for the late follow up! The PR went unnoticed as it seemed the build was still failing. Thanks for the awesome PR and will process it further!

**Comment by xaviergonz** [comment]
Can't there be a threshold before coveralls marks a PR as failing?

**Comment by mweststrate** [comment]
Merging, thanks a lot!

**Comment by mweststrate** [comment]
Fixed and released in 4.9.0 / 5.9.0

**Pull request closed without merging**
