### PR TITLE
correctly expose flow typings

### PR DESCRIPTION
**Pull request by Kriegslustig**
With this PR consumers can use the Flow type definitions without needing any configuration.

### CODE REVIEW

**Comment by Kriegslustig** [comment]
Apparently references don't work in titles... #1232

**Comment by mweststrate** [comment]
@Kriegslustig just double check: you verified this will work when installing the package and import stuff using `import { x } from "mobx"`?

**Comment by Kriegslustig** [comment]
Yes, this works. With one caveat though, consumers will need to remove MobX from flow config `[libs]` section. I will update the README accordingly.

```
--- a/.flowconfig
+++ b/.flowconfig
@@ -5,7 +5,6 @@
 [include]
 
 [libs]
-./node_modules/mobx/lib/mobx.js.flow
 /flow-typed
 
 [options]
```

**Comment by Kriegslustig** [comment]
I documented it in the README. Should I also write something into the changelog?

**Comment by mweststrate** [comment]
@Kriegslustig yep, please put it in the changelog.md as well :)

**Comment by Kriegslustig** [comment]
done 👍

**Comment by mweststrate** [comment]
Thanks! Merged and will release soon as 3.4.0

**Comment by zhaocnus** [comment]
@Kriegslustig, @mweststrate:

I think a lot of people might accidentally update MobX from v3.3.3 to v3.4.0 (by just removing and reinstalling all the node_modules). If they do that but they still use MobX's flow type definition based on the old [README](https://github.com/mobxjs/mobx/tree/c6dd0d852157fcebfaafc2d9ac119eb6a7f6c65f#flow-support), they will get a ton of flow errors. 

I have a blog post to explain this: https://github.com/zhaocnus/mobx-flow-typed-test

Maybe we need to provide more info in the readme?

**Comment by Kriegslustig** [comment]
@zhaocnus have you read the [changelog](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#340)? Maybe we can extend this information, if it's not sufficient.

**Comment by zhaocnus** [comment]
@Kriegslustig Yes I think extending the information will be helpful (especially for people who are not an expert in flow). But it not necessary. 

I did check the changelog but I wish I have seen it earlier :) 

This is how I encountered the issue:

1. I did a refresh install of all my node modules (removed node_modules folder and package-lock.json, and run `npm i`). I have `"mobx": "^3.2.2",` in my package.json. `npm i` installed mobx 3.4.1. 
2. I still have `node_modules/mobx/lib/mobx.js.flow` in `.flowconfig`

So this exposes all the mobx type definitions to the global scope, and flow throws a lot of errors. It took me a while to figure the issue. I hope I could have checked the README and changelog earlier. 

So I figure adding some more info might save other people's time later.

**Comment by mweststrate** [comment]
PR for changelog is welcome! (and tip: make sure that removing node_modules
doesn't upgrade your modules unintentionally. Use yarn, npm lock files or
npm shrinkwrap, without them it is impossible to create reliable /
reproducible builds for your project)

Op vr 29 dec. 2017 om 09:56 schreef Luca Nils Schmid <
notifications@github.com>:

**Comment by zhaocnus** [comment]
@mweststrate Thanks for the tip! I've learned my lesson. I will create a PR.

**Pull request merged**
