### PR TITLE
simplify code contributions + reviews by fully automating the dev setup.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! :slightly_smiling_face: 

As discussed in #2316 This Pr simplifies code contributions and reviews by fully automating the dev setup with Gitpod (a free online VS Code like IDE). 

With a single click, it'll launch a ready to code workspace with everything setup.

You can give it a try on my fork of the repo via this link:

https://gitpod.io/#https://github.com/nisarhassan12/mobx

this is how it looks:

image

Also for having these review comments in PRs and [pre-built](https://www.gitpod.io/docs/prebuilds/) workspaces, the Gitpod App has to be installed https://github.com/apps/gitpod-io I have added the configuration required you just have to install the app.

image

The app can only be installed by individual developers on their own account (i.e. there is no org billing or so). It can then be enabled/disabled & configured for any accounts or organizations that the developer maintains:

image

Please let me know if there is anything else that can be improved or need some work I'll be happy to help :slightly_smiling_face: .

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Also once this PR is merged we'll add this project to https://contribute.dev

image

**Comment by FredyC** [comment]
Thank you, I am really curious if people will be using this :) I like that it opens preview for the docs, it's useful. Also fixed `npm run perf` is great except now with both terminals running something, there is no room to run it directly. It might make sense to run it initially in another tab so contributor can see it passing and is able to rerun it later.

Can you also add a similar description from readme to CONTRIBUTING.md?

**Comment by nisarhassan12** [comment]
@FredyC Thanks! I have made the changes that you requested.

This is how it looks now:

image

**Comment by FredyC** [comment]
Oh, neat, named tabs :) Let's roll with it although I don't have permission to add that bot.

@mweststrate @xaviergonz @urugator @ItamarShDev  Can one of you do it?

**Comment by nisarhassan12** [comment]
Thanks! @FredyC please let me know if there are any VS Code extensions that can enhance the working experience for this project. Gitpod also supports them.

**Comment by FredyC** [comment]
Prettier
EditorConfig
ESLint
Markdown All in One

**Comment by nisarhassan12** [comment]
Thanks! @FredyC I have installed the VS Code extensions.

Also `EditorConfig` is a built-in extension in Gitpod extension.

**Comment by FredyC** [comment]
Thanks, I am going to merge this and try to persuade someone to add that bot :)

**Comment by nisarhassan12** [comment]
Mobx is now listed on https://contribute.dev
image

**Pull request merged**
