### PR TITLE
bugfix: allow changing while observable array initialization

### PR DESCRIPTION
**Pull request by kuitos**
fixed: https://github.com/mobxjs/mobx/issues/1568

* [x] Added unit tests

### CODE REVIEW

**Comment by mweststrate** [comment]
Thanks!

**Comment by jspopisno1** [comment]
@mweststrate 

Our project is now switching to 4.3.1 and we also found bug #1568 .
Was glad to see this bugfix, but wondering why it's not in 4.3.1 (as it's reported in 4.3.0) ?
Found code in 
 4.3.1 as https://github.com/mobxjs/mobx/blob/2c82242bb2ff6582c42e3963b5f83f98475541a9/src/types/observablearray.ts#L338

Are we using it incorrectly or is it really a bug in latest 4.3.x ?

Hope for further info. and heaps of thanks!

**Comment by mweststrate** [comment]
Please open a new issues when you run into something. Commenting on a closed item gives only a 20÷ chance something sees your comment. 

Please open a new issue,  refer to this one and we'll look into it

**Comment by jspopisno1** [comment]
@mweststrate Just drop here to confirm when this bugfix is going to get released, and no problem now (I saw 4.3.2) !

thanks very much !!! ;)

**Pull request merged**
