### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by iChenLei** [comment]
Yah, finally, dependabot is coming. 😄

**Comment by kubk** [comment]
Hi @naveensrinivasan Thank you for the contribution. I see that most of the actions are up-to-date already:

https://github.com/mobxjs/mobx/blob/63698d0681988194bac5fc01851882b417b35f18/.github/workflows/release.yml#L14

https://github.com/mobxjs/mobx/blob/63698d0681988194bac5fc01851882b417b35f18/.github/workflows/release.yml#L20

https://github.com/mobxjs/mobx/blob/63698d0681988194bac5fc01851882b417b35f18/.github/workflows/release.yml#L29

All of them refer to master. The only action with a fixed version is coverallsapp/github-action

https://github.com/mobxjs/mobx/blob/63698d0681988194bac5fc01851882b417b35f18/.github/workflows/coveralls.yml#L31

@urugator @mweststrate Do we use coveralls at all?

**Review by kubk — APPROVED** [review]

**Comment by naveensrinivasan** [comment]
A friendly ping!

**Comment by urugator** [comment]
Thank you for the PR. Would love to provide any feedback, but I am not familiar with these enough. Same goes for #3421.
If someone knows better, feel free to merge (or let me know if you don't have permissions).

**Comment by naveensrinivasan** [comment]
> Thank you for the PR. Would love to provide any feedback, but I am not familiar with these enough. Same goes for #3421.
> If someone knows better, feel free to merge (or let me know if you don't have permissions).

Thanks, I have provided the links with all the information. HTH.

**Review by mweststrate — APPROVED** [review]

**Review by iChenLei — APPROVED** [review]

**Pull request merged**
