### PR TITLE
fix Flow typings for flow() - mobx4

### PR DESCRIPTION
**Pull request by vonovak**
same as #2164 for mobx 4

### CODE REVIEW

**Comment by FredyC** [comment]
Thanks!

**Comment by vovkasm** [comment]
With mobx 4.15.0 I have this error now:
```
node_modules/mobx/lib/api/flow.d.ts:9:108 - error TS2304: Cannot find name 'AsyncGenerator'.

9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                                             ~~~~~~~~~~~~~~


Found 1 error.

npm ERR! Test failed.  See above for more details.
```

Downgrade to 4.14.1 fixed the problem.

**Comment by vovkasm** [comment]
@vonovak Above error because AsyncGenerator defined only in lib.es2018.asyncgenerator.d.ts

@FredyC Does this mean that mobx (even 4.x) can be used only with `"lib": ["es2018"]` in tsconfig?

**Comment by FredyC** [comment]
You are commenting on the wrong PR, this is about FlowType. Please open the new issue instead.

There is a requirement to use TS 3.6 since the last release. Not sure about `lib`, that might wrong.

**Comment by vovkasm** [comment]
Thank you! And sorry, not understand that this about flowtype. Just found this ticket with search. Will create distinct bug report.

**Pull request merged**
