### PR TITLE
fix: self and global error in alipay appx

### PR DESCRIPTION
**Pull request by doxiaodong**
fix https://github.com/mobxjs/mobx/issues/2070

Thanks for taking the effort to create a PR!

If you are creating an extensive PR, you might want to open an issue with your idea first, so that you don't put a lot of effort in an PR that wouldn't be accepted. Please prepend pull requests with `WIP: ` if they are not yet finished
PR checklist:
no-necessary

Feel free to ask help with any of these boxes!

The above process doesn't apply to doc updates etc.

### CODE REVIEW

**Comment by FredyC** [comment]
Thanks, LGTM. Please add the following to changelog (only in this PR).

```
# 5.13.1 / 4.13.1

* Don't use `global` and `self` keywords unless defined. Fixes [#2070](https://github.com/mobxjs/mobx/issues/2070).
```

**Comment by doxiaodong** [comment]
I change the `mobx` and use it.  when will you publish ?

**Comment by FredyC** [comment]
Sorry, but not that soon. Feel free to use https://github.com/whitecolor/yalc or alternatives if you are in a hurry.

**Comment by doxiaodong** [comment]
Can you release this please.

**Comment by doxiaodong** [comment]
@FredyC can you please release this.

**Pull request merged**
