### PR TITLE
Fi3ework fix #1803

### LINKED ISSUE #1803: trace utility logs invalid info
Hello.

I've found that `trace()` utility is useless in some cases. Check the code (also available as jsfiddle: https://jsfiddle.net/Strate/0wyp6vhk/11/):
```js
const {observable, computed, autorun, trace, runInAction} = mobx;

const a = observable.box(null, {name: "a"});

const b = computed(() => {
  void a.get();
  return 2;
}, {name: "b"})

const c = observable.box(null, {name: "c"});

const final = computed(() => {
  trace();
  c.get();
  b.get();
  return {}
}, {name: "final"})

autorun(() => {
  console.log(final.get());
})

runInAction(() => {
  a.set(1);
  c.set(1);
})

runInAction(() => {
  a.set(2);
  c.set(2);
})
```
Actual log becomes:
```
[mobx.trace] 'final' tracing enabled
{}
[mobx.trace] 'final' is invalidated due to a change in: 'b'
{}
[mobx.trace] 'final' is invalidated due to a change in: 'b'
{}
```

But expected log is:
```
[mobx.trace] 'final' tracing enabled
{}
[mobx.trace] 'final' is invalidated due to a change in: 'c'
{}
[mobx.trace] 'final' is invalidated due to a change in: 'c'
{}
```

Because `final` computed recomputes only when `c` changes, and `b` actually not changed.

### PR DESCRIPTION
**Pull request by mweststrate**
Follows up on #1901

### CODE REVIEW

**Comment by mweststrate** [comment]
closing for inactivity

**Comment by Strate** [comment]
I would like to continue work on this

**Comment by FredyC** [comment]
@Strate Do you still want to continue? It needs to resolve conflicts and I am sure if it's worth the effort with upcoming V6. Closing and feel free to reopen (again) if you want.

**Comment by Strate** [comment]
@FredyC right now let it be deleted

**Pull request closed without merging**
