### PR TITLE
Update react-integration.md

### PR DESCRIPTION
**Pull request by kimyoungjae96**
I fixed the example. check please!

### CODE REVIEW

**Comment by iChenLei** [comment]
I think you didn't understand this example, let me explain it.

```diff
// 1
- const TimerView = observer(({ offset }) => {
+ const TimerView = observer(() => {

// 2
- return <span>Seconds passed: {timer.offsetTime}</span>
+ return <span>Seconds passed: {timer.secondsPassed}</span>
```
1 -- This example for `deriving computeds from props`, the `offset` from `props`, so why delete it ?
2 -- offsetTime is a `getter`, to show the `offset` and `secondsPassed`'s reactive, only show `secondsPassed` can't present `deriving computeds from props`.
```js
        get offsetTime() {
            return this.secondsPassed - this.offset // Not 'offset' from 'props'!
        }
```

**Comment by kimyoungjae96** [comment]
oh, I edited useEffect and observables example not the deriving computeds from props exmaple.

**Comment by iChenLei** [comment]
Oh, sorry. Thanks for example fix.

**Review by iChenLei — COMMENTED** [review]
LGTM

**Pull request merged**
