### PR TITLE
Change types for IObjectWillChange and IObjectDidChange to generic

### LINKED ISSUE #2330: Proposal: Change type IObjectWillChange to generic
Now the type `IObjectWillChange` is just union type of two type which both contains a field `object`:
```typescript
export declare type IObjectWillChange = {
    object: any;
    type: "update" | "add";
    name: PropertyKey;
    newValue: any;
} | {
    object: any;
    type: "remove";
    name: PropertyKey;
}
```
If I understand correctly the `object` is just instance of current store:
image

So I propose a small change to this type: make `IObjectWillChange` the generic type:
```typescript
export declare type IObjectWillChange<T = any> = {
    object: T;
    type: "update" | "add";
    name: PropertyKey;
    newValue: any;
} | {
    object: T;
    type: "remove";
    name: PropertyKey;
}
```
**Pros:**
1️⃣ Stronger default typings
2️⃣ Autocomplete
3️⃣ Backward compatibility
4️⃣ Provide an possibility make stronger typings in other places

**Cons:**
I don't see it

If this change is ok I can make an PR but point me what should be modified also?

**How I see using this:**
```typescript
type UserStoreObservables = {
    firstName: string
    lastName: string
}

type UserStore = UserStoreObservables & {
    getFullname: () => string
}

class UserStore implements UserStore {
    @observable firstName = ''
    @observable lastName = ''
    constructor() {
        intercept(this, (change: IObjectWillChange<UserStoreObservables>) => {
            // … do some stuff
        })
    }

    getFullname = () => this.firstName + '' + this.lastName
}

```

### PR DESCRIPTION
**Pull request by inoyakaigor**
Resolves #2330 

### Code change checklist
-   [x] Updated typings
-   [ ] Updated changelog
-   [ ] Added/updated unit tests
-   [ ] Updated `/docs`. For new functionality, at least `API.md` should be updated
-   [ ] Verified that there is no significant performance drop (`npm run perf`)

<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2332"></a>

### CODE REVIEW

**Comment by FredyC** [comment]
I think you had some older fork. We have merged V4 and V5 into the master branch and you are modifying non-existing `src/types`. Please rebase on the latest master do the change for both versions.

**Comment by inoyakaigor** [comment]
Hmm… Something going wrong. I forked yesterday. However I will fix it

**Comment by inoyakaigor** [comment]
@FredyC All done

**Comment by FredyC** [comment]
Thanks

**Pull request merged**
