### PR TITLE
Run prettier

### PR DESCRIPTION
**Pull request by FredyC**
@mweststrate Merge it when you want. I noticed in #2382 that @faassen has a bunch of styling changes. It's probably better to do it separately as that PR might take a while.

<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2388"></a>

### CODE REVIEW

**Comment by mweststrate** [comment]
Could you drop de changes to files in `docs/`? otherwise the merge conflicts will be horrible (git isn't smart enough to follow along even if that branch is prettified, if there are other changes as well). 

Thinking of it, I think we could just work on the docs on the same branch v6, that is probably more straightforward @faassen? And makes also these kind of changes easier.

**Comment by FredyC** [comment]
I don't think it's a problem, these are just whitespace and @faassen already have these changes in that branch. But yea, working on docs directly in this branch would be probably better long term.

**Comment by FredyC** [comment]
Ah and another PR https://github.com/mobxjs/mobx/pull/2389 that has some Prettier styling. I wonder @mweststrate, do you have Prettier installed in your IDE? It seems like it's not formatting it for you. Although it should be done in commit phase unless you are skipping it deliberately.

**Comment by mweststrate** [comment]
@FredyC yeah that is correct, I had disabled it for a while because it messed up snapshots tests every time. But in the end it turned out that was caused by vscode's trim trailing whitespace setting, so it should be good from know on again.

**Pull request merged**
