### PR TITLE
Named autorun function

### PR DESCRIPTION
**Pull request by jamiewinder**
Implements optionally named autoruns suggested here:
https://github.com/mobxjs/mobx/issues/293

### CODE REVIEW

**Comment by mweststrate** [comment]
Thanks for the PR and looking good! Some notes / room for improvements (don't feel obliged to do so, but help is appreciated nonetheless :))

* [ ] add unit tests
* [ ] update docs
* [ ] add to release notes
* [ ] introduce optional name param to `autorunAsync`, `when` and `reaction` as well?

**Comment by jamiewinder** [comment]
Thanks for the feedback so far!

I've now added the same parameter to `autorunAsync`, `when`, and `reaction`. I've hopefully kept the same logic and defaults (I notice `autorunAsync` has delay default to 1ms, and reaction defaults to 0ms - intentional?). 

I haven't added the parameter to `autorunUntil` - presumably if it's deprecated, it isn't necessary?

I don't mind updating the documentation once you're happy with the code changes. Unit tests aren't my strong point however, so I might not be the best person to write those!

**Comment by jamiewinder** [comment]
Just to add - since the `name` is now determined in the `when` function rather than `autorun`, we have the opportunity to default to `When@###` rather than `Autorun@###` as it will currently. This appears to fit with what the defaults are in `autorunAsync` (AutorunAsync@###) and `reaction` (Reaction@###).

**Comment by mweststrate** [comment]
Merged the changes and will be part of 2.3. Thanks!

**Comment by jamiewinder** [comment]
Great! Not sure if my last comment was noticed (about defaulting the name of a `when` to When@ rather than Autorun@) but it can be updated if needed. Happy to help, and many thanks for the library (and accepting my first every GitHub PR!)

**Comment by mweststrate** [comment]
@jamiewinder thanks! missed that indeed :) Thanks for contributing!

**Pull request merged**
