### PR TITLE
ObservableArray#findIndex

### PR DESCRIPTION
**Pull request by leader22**
refs #934 

Implement `ObservableArray#findIndex` to accepts 3rd arguments like `ObservableArray#find`.

* [x] Added unit tests
* [x] Added typescript typings
* [x] Verified that there is no significant performance drop (`npm run perf`)

I'll send another PR for updating docs later. -> #938

### CODE REVIEW

**Comment by leader22** [comment]
@mweststrate 

It seems CI fails with your latest commit https://github.com/mobxjs/mobx/commit/1cc4f5173f6da74a447c94615a62fb9c1380b397 
Even on branch `master`, `npm run full-test` seems to fail.

Would you be able to check it?(or my mistakes are there?)

**Comment by mweststrate** [comment]
@leader22 sorry, my mistake! Fixed the testsuite, so pulling in latest changes should fix it

**Comment by leader22** [comment]
I've just finished my work.
Would you please check this PR and #938 for docs?

**Comment by capaj** [comment]
LGTM. Good job @leader22 !

**Comment by mweststrate** [comment]
Agreed! Can be merged and released as well

**Pull request merged**
