### PR TITLE
fix update array event using this as object instead of proxy

### PR DESCRIPTION
**Pull request by xaviergonz**
I just noticed that array "splice" would return the array proxy as object, yet "update" would return the array itself
This PR fixes that

### CODE REVIEW

**Comment by ItamarShDev** [comment]
Seems OK
any possible side affects we can think of?
maybe add some tests?( i am not sure they will really add any value)

**Comment by xaviergonz** [comment]
None that I can think of, since the other one was updated to use proxy I can imagine this one was not just due to an oversight

**Comment by ItamarShDev** [comment]
Let's merge then :)

**Comment by xaviergonz** [comment]
merged, don't think this needs backporting anyway since mobx 4 does not use proxies

**Comment by mweststrate** [comment]
Released as 4.10.0 / 5.10.0

**Pull request merged**
