### PR TITLE
Skip redundant comparison

### PR DESCRIPTION
**Pull request by MoonBall**
### Code change checklist

-   [x] Added/updated unit tests
-   [x] Updated changelog
-   [x] Updated `/docs`. For new functionality, at least `API.md` should be updated
-   [x] Verified that there is no significant performance drop (`npm run perf`)

<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2405"></a>

### CODE REVIEW

**Comment by FredyC** [comment]
@MoonBall Is there some actual issue for this PR or just your assumption about performance? You haven't added any tests or explained anything.

Also note, that you are contributing to the upcoming V6 which you are probably not using yet.

**Comment by MoonBall** [comment]
There is no actual issue. It's only about performance. 

Should I make the pr for master branch?

**Comment by FredyC** [comment]
@mweststrate Probably better for you to decide this.

**Comment by mweststrate** [comment]
@MoonBall, no this branch is fine. I guess the correctness of the change cannot be proven beyond that all tests still pass :) But it is years since this code is written, so a little rationale why the truth branch is always taken, to be able to think about the correctness without fully diving what is happening here again😅. Especially since the branch isn't taken always, I want to make sure that I understand that making the update always, doesn't slow anything down anywhere else:

Screen Shot 2020-07-23 at 20 24 42

**Comment by MoonBall** [comment]
@mweststrate Hi, how do you get the execution count, the 3908x and 14x in your image.

**Comment by mweststrate** [comment]
@MoonBall  yeah, run `yarn test:coverage` and than open `coverage/lcov-report/index.html`

**Comment by MoonBall** [comment]
@mweststrate Thanks. I find that the amount of duplicated observing is only 4 times when I run `yarn test`.
So I close the PR.

**Pull request closed without merging**
