### PR TITLE
docs: Add Ukraine flag

### PR DESCRIPTION
**Pull request by mweststrate**
Belated, as it kept lingering on my to-do list, but added a Ukrainian flag as a tiny token of respect to their fight against the Russian invasion.

### CODE REVIEW

**Review by iChenLei — APPROVED** [review]
LGTM

**Review by kubk — APPROVED** [review]

**Comment by kubk** [comment]
@mweststrate Where is it going to be applied? The PR is merged and it looks like it was deployed, but I can't find the banner.

Screen Shot 2022-08-13 at 20 25 46

**Comment by mweststrate** [comment]
Hmm, other changes aren't visible as well, I guess the deployment process
is broken.

**Comment by mweststrate** [comment]
yes. If it bother you feel free to skip this library.

**Pull request merged**
