### PR TITLE
Remove confusing Run button in Getting Started #GoodnessSquad

### PR DESCRIPTION
**Pull request by eladnava**
As per https://github.com/mobxjs/mobx/issues/634#issuecomment-273297901.

### CODE REVIEW

**Comment by mattruby** [comment]
Would we be better off taking #647 ?

**Comment by eladnava** [comment]
Sorry about that, #647 was not linked in #634 so I did not know a PR had already been submitted.

If the maintainers feel that #647 is a better solution, please feel free to close this.

**Comment by mweststrate** [comment]
I'll merge this, and clean it up further. Thanks!

**Comment by eladnava** [comment]
Excellent, thank you! 👍

**Pull request merged**
