### PR TITLE
resolves: examples execution is slightly out of order #634

### PR DESCRIPTION
**Pull request by neil-rubens**
some of the code was executed ahead of time; removed those references.

### CODE REVIEW

**Comment by mweststrate** [comment]
Thanks! I'll (or somebody else) will test this soon

**Comment by mweststrate** [comment]
Hmm.. shouldn't the buttons not just be removed them? The code snippets themselves have no visible side effects. Or maybe the text then should state nothing visible changed?

**Comment by neil-rubens** [comment]
Good point.  To avoid confusion, it would be good to remove buttons for the code blocks that have no visible effect.

**Comment by mweststrate** [comment]
Thanks! I'll merge this, review and process it further

**Pull request merged**
