### PR TITLE
feature(api): tell consumers when their objects are observable

### PR DESCRIPTION
**Pull request by spiffytech**
See issue #483.

### CODE REVIEW

**Comment by mweststrate** [comment]
Thanks for the PR, will consider this for the next release

**Comment by mweststrate** [comment]
This typing is actually not correct, an object being converted to an observable is not an `IObservable` itself, it has an IObservable backing object instead, as defined here: https://github.com/mobxjs/mobx/blob/aa8ea15573cf27e0128235b334ca53c9aaceeae1/src/types/observableobject.ts#L51. I don't feel that exposing that interface however adds value, it is just the internal administration.

What could be done is introducing an empty `IObservableObject` interface. That has in itself not that much value, except that it could be used as typeguard for `isObservableObject`, so that people can express that they want to have some observable object as arguments to their functions. see also: https://github.com/mobxjs/mobx/pull/487

**Comment by spiffytech** [comment]
Having `observable({})` return `T & IObservableObject`, with `IObservableObject` being an empty interface would satisfy my request.

Just to be clear, I'm not looking for TypeScript's type guards - they're designed to enhance type safety of code branches used in runtime type checks. I'm looking to improve compile-time checks, like so:

```typescript
@action
function updateMyFoo(foo: MyInterface & IObservableObject) {
  foo.some_prop = true;  // triggers observers
}

const foo: MyInterface = {some_prop: false};
updateMyFoo(foo);  // compiler error - not observable

const observable_foo = observable(foo);  // MyInterfyace & IObservableObject
updateMyFoo(observable_foo);  // success
```

**Comment by mweststrate** [comment]
Yep, that makes sense to me :)

**Comment by Strate** [comment]
@spiffytech unfirtunatelly, due to structural typing system limitation (which TYpeScript is based on), you will not receive compile time errors here, because TS will not check *interfaces* on object, it will check *structure* of object. It means, that having empty interface is almost useless.
There is a suggestion to improve TS in this part, but still needs proposal: https://github.com/Microsoft/TypeScript/issues/202

**Comment by mweststrate** [comment]
dôh indeed

**Comment by Strate** [comment]
There is a cool trick, I've found in comments: https://github.com/Microsoft/TypeScript/issues/202#issuecomment-50199713
Maybe we could use it here :)

**Comment by spiffytech** [comment]
@Strate Can you clarify how your suggestion works with empty interfaces? The below code sample compiles for me, when it should produce an error - `updateMyFoo()` is still allowing an argument of type `MyInterface`.

```typescript
interface IObservableObject {}

interface MyInterface {
    some_prop: boolean;
}

function updateMyFoo(foo: MyInterface & IObservableObject) {
    foo.some_prop = true;
}

const foo: MyInterface = {some_prop: false};
const observable_foo = <MyInterface & IObservableObject> foo;

updateMyFoo(foo);  // compiles :(

updateMyFoo(observable_foo);  // compiles
```

**Comment by spiffytech** [comment]
@mweststrate May I assume from your previous comment that you wouldn't be comfortable exposing the `IIsObservableObject` interface (on an identical interface named `IObservableObject`), even if it's the only way to satisfy this feature request?

**Comment by mweststrate** [comment]
@spiffytech indeed, the `mobx$` is an internal concept and should be hidden to the outside world as much as possible. 

something like `interface IObservableObject { "observable-object-marker": IObservableObject }` is the trick I think. That attribute doesn't have to be exists at runtime, it is just that the compiler needs to think that it is returned from the `observable` function :)

**Comment by spiffytech** [comment]
Ah, I see! Confirmed, that makes the appropriate error occur in my code sample.

I'll update my full request with this.

**Comment by mweststrate** [comment]
@spiffytech did you by any chance proceed on this one ?

**Comment by spiffytech** [comment]
Yeah, I adopted what we discussed, added the type guard to `isObservable`, and added some unit tests for both.

I was hoping to find a way to unit test the failure case for the type guard, but everything I could think of prevented the TypeScript tests from compiling.

**Comment by mweststrate** [comment]
Just merged, thanks a lot!

**Pull request merged**
