### PR TITLE
Computed / Reaction comparer

### PR DESCRIPTION
**Pull request by jamiewinder**
Addresses #802 and #943

Allows a custom comparer to be specified on computed values and properties. Useful for situations where the inbuilt identity and structural comparisons aren't sufficient. 

This should be completely backwards compatible with the current major version.

Still to do:
* [x] Update ComputedValue JSDoc
* [x] Change createComputedDecorator to accept equals comparer rather than boolean 'struct'
* [x] Add `@computed.equals(equals: IEqualsComparer)` 

PR checklist:
* [x] Added unit tests
* [ ] Updated changelog
* [ ] Updated docs (either in the description of this PR as markdown, or as separate PR on the `gh-pages` branch. Please refer to this PR). For new functionality, at least [API.md](https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md) should be updated
* [x] Added typescript typings
* [x] Verified that there is no significant performance drop (`npm run perf`)

### CODE REVIEW

**Comment by jamiewinder** [comment]
WIP because of a couple of build / test issues which I'd appreciate help with:

I was hoping to change the signature of `createComputedDecorator` from:

```
function createComputedDecorator(compareStructural: boolean)
```
to
```
function createComputedDecorator(equals: IEqualsComparer<any>)
```
and therefore change the following lines:
```
const computedDecorator = createComputedDecorator(false);
const computedStructDecorator = createComputedDecorator(true);
```
to...
```
const computedDecorator = createComputedDecorator(defaultComparer);
const computedStructDecorator = createComputedDecorator(structuralComparer);
```
However, I can't because for some reason they're `undefined` at this point; I have to access them late for the values to be set. I think this is because of the custom build script which is calling the above lines before the `defaultComparer` and `structuralComparer` variables are set. 

Any advice on what the problem here might be?

Also, I want to add a function similar to `@computed.struct` which will allow the custom comparer to be specified for class properties. Something similar to:

```typescript
const isSameid = (a, b) => a.id === b.id;

class Foo {
     @computed.equals(isSameid ) get selected() {
        ...
     }
}
```
I'll do this once I've solved my build problem, but any comments on the name would be appreciated.

I'll sort the docs, tests, etc. once the above are sorted. Any comments welcome!

**Comment by jamiewinder** [comment]
I started writing some tests for this, and come up with something I'd like input on:

Do we think that I should hide away the change detection for the first value, and from/to CaughtException such that:
- `(no value) -> value` is considered a change, does not call the comparer
- `value -> CaughtException` is always considered a change, does not call the comparer
- `CaughtException -> value` is always considered a change, does not call the comparer
- `CaughtException -> CaughtException` is always considered a change, does not call the comparer

As such, there won't be any 'surprising' values being passed to the comparer function; if you have a basic computed property like so:

```typescript
get time() {
    return { hour: this.hour, minute: this.minute }
}
```
I'll *know* that if I add an `.equals` comparer to this, it can be written simply as:
```typescript
const sameTime = (a, b) => a.hour === b.hour && a.minute === b.minute;
```
i.e. i don't have to check if `a` or `b` is undefined, or a CaughtException.

**Comment by mweststrate** [comment]
@jamiewinder sorry for not having time earlier to look into this! Imho `(no value) -> value` can be considered always a change indeed, but only if you can express this to only happen for the first run. As `undefined -> value` should call the comparer generically speaking.

Circular references in the build process are annoying indeed. I want to move to rollup in the near feature, as that hopefully fixes without blowing the bundle size. In the mean time, if it is still an issue, just let me know and I'll investigate it. Moving imports to top / bottom, or using functions instead of constants (as functions get hoisted but constant assignments not) can often help

**Comment by jamiewinder** [comment]
No problem at all, we're all busy! 

The behaviour of the `equals` comparer is currently just that. A comparer along the lines of `(a, b) => a.id === b.id` doesn't (necessarily) need to guard against the arguments being undefined as it'll only be called with values returned from the computed property, or the reaction expression.

I've included some tests which I believe covers this for both computed-s and reaction-s. 

As far as I'm aware, the only things missing is the documentation, which I can do if we're happy with everything else.

Thanks.

**Comment by mweststrate** [comment]
@jamiewinder this PR looks great, let's proceed with it!

Could you take at the the following points:
* [ ] A unit test where `computed` with comparer is used, without using decorators, (e.g. extendObservable({ prop: computed(expr, getter, setter, comparer})`
* [ ] Docs & changelog updates
* [ ] I think it is nice to not expose the compare functions on top level, but at a namespace to group them together? Suggestion: `compare.structural`, `compare.identity`, `compare.default`?

Thanks a lot so far! I think this is a great PR :)

**Comment by jamiewinder** [comment]
I've made the code changes (updated to master, moved comparers to a namespace, non-decorator tests). I can't seem to figure out why the CI is now failing? 
```
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (native)
    at r (C:\Projects\GitHub\mobx\lib\mobx.js:2:560)
```
I'll keep looking, but can you spot anything obvious?

**Comment by mweststrate** [comment]
This means that rollup didn't properly resolve ciruclar dependencies, and
some inheritance is failing because the base class is not defined. Usually
this needs to be fixed by moving some imports a round, for example to the
bottom of a file


Op do 29 jun. 2017 om 11:47 schreef jamiewinder <notifications@github.com>:

**Comment by jamiewinder** [comment]
Thanks for the tip! Seems to be sorted. Only thing left is documentation, which I'll try to update soon.

**Comment by jamiewinder** [comment]
Documentation in separate pull request #1084

**Comment by mweststrate** [comment]
Released as 3.2.1. Thanks!

**Pull request merged**
