### PR TITLE
Small, pedantic grammar fixes

### PR DESCRIPTION
**Pull request by elliottkember**
Hello! Mobx is great and I like it very much. I noticed a few apostrophes out of place and fixed them. If I were smarter I would fix bugs or write code but I will leave that to the smart people.

### CODE REVIEW

**Comment by mattruby** [comment]
Thanks!

**Comment by elliottkember** [comment]
@mattruby More than welcome, but why did you close this instead of merging it?

**Comment by mattruby** [comment]
Sorry, I meant to merge it!

**Comment by elliottkember** [comment]
In that case I'm glad I asked!

**Comment by mattruby** [comment]
Haha!

**Pull request merged**
