### PR TITLE
[README] - Beautify and update contributing section

### PR DESCRIPTION
**Pull request by ItamarShDev**

### CODE REVIEW

**Comment by mweststrate** [comment]
@ItamarShDev there are a lot of whitespace / formatting changes. They look good, but would you mind making sure they are part of the prettier config in the repo, so that we all produce the same markdown on save? Thanks!

**Comment by ItamarShDev** [comment]
Will check. Thanks @mweststrate

**Comment by ItamarShDev** [comment]
@mweststrate you were right, i guess it was the `prettier` vscode extension on my home laptop
Should remove it

**Comment by ItamarShDev** [comment]
@mweststrate please approve merging

**Comment by mweststrate** [comment]
Merged! Thanks :)

**Pull request merged**
