### PR TITLE
docs: Fix misleading direction

### PR DESCRIPTION
**Pull request by brunocoelho**
Hi there.

The example is below the explanation, not above.

### CODE REVIEW

**Comment by kubk** [comment]
@brunocoelho Nice catch 👍

**Comment by urugator** [comment]
Perhaps it could be formulated better, but I think the original statement is correct:

***In the above example**, the TimerView component **would not** react to future changes **if it was defined as follows**,*

It says what *would* happen to the example [*above*](https://mobx.js.org/react-integration.html#using-local-observable-state-in-observer-components), if you would change `TimerView` definition, as shown in *following* (below) snippet (it's not a complete example).

**Comment by brunocoelho** [comment]
@urugator I agree with you. Misleading is not the right word, maybe just a little confusing.
What do you think if we change to:

~~In the above example,~~ _The `TimerView` component would **not** react to future changes if it was defined as follows..._

At this point, we know what TimerView is about because it was the last example used.

After your explanation, I'm fine leaving the documentation unchanged though.

**Comment by urugator** [comment]
> What do you think if we change to:

Agree, I think it's sufficient and less confusing, thank you.

**Comment by brunocoelho** [comment]
Cool, I will close this PR and create a new one with the change discussed.

**Pull request closed without merging**
